[tool.briefcase]
project_name = "WOL_Dayepao"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/wol_dayepao"
license = "BSD license"
author = 'Dayepao'
author_email = "dayepao@example.com"

[tool.briefcase.app.wol_dayepao]
formal_name = "WOL_Dayepao"
description = "Wake up the specified host through preset trigger conditions"
icon = "src/wol_dayepao/resources/wol_dayepao"
sources = ['src/wol_dayepao']
requires = [
]


[tool.briefcase.app.wol_dayepao.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.wol_dayepao.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.wol_dayepao.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.wol_dayepao.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.wol_dayepao.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.wol_dayepao.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.wol_dayepao.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.wol_dayepao.web]
requires = [
    # Workaround; toga-web 0.3.0.dev38 doesn't include toga-core as a dependency.
    "toga-core>=0.3.0.dev38",
    "toga-web>=0.3.0.dev38",
]
style_framework = "Bootstrap v4.6"
