name: keepalive

on:
  workflow_dispatch:
  schedule:
    - cron: 0 13 1,15 * *

jobs:
  Update_keepalive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [personal_actions, backup]
    steps:
      - name: Set time zone
        run: |
          sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/${{ matrix.repo }}
          path: ${{ matrix.repo }}
          token: ${{ secrets.GH_PAT }}

      - name: Update keepalive file
        run: |
          cd ${{ matrix.repo }}
          echo "$(date)" > keepalive
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add keepalive
          git commit -m "Update keepalive"
          echo "${{ matrix.repo}} 保活成功" > tmp_message_${{ matrix.repo }}

      - name: Upload tmp_message
        uses: actions/upload-artifact@v4
        with:
          name: tmp_message_${{ matrix.repo }}
          path: tmp_message_${{ matrix.repo }}

  Push_message:
    runs-on: ubuntu-latest
    steps:
      - name: Set time zone
        run: |
          sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install httpx

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download tmp_message
        uses: actions/download-artifact@v4
        with:
          path: tmp_message

      - name: Compile message
        run: |
          message=""
          for file in tmp_message/*; do
            message="${message}$(cat $file)\n\n"
          done
          message=$(echo -n "$message" | sed 's/\n\n$//')
          echo "MESSAGE=${message}" >> $GITHUB_ENV

      - name: Push message
        env:
          QYWX_AM: ${{ secrets.QYWX_AM }}
        run: |
          CURRENT_TIME=$(date "+%Y-%m-%d %H:%M:%S %Z(%z)")
          MESSAGE_CONTENT="${CURRENT_TIME}\n\n${MESSAGE}"
          if [ "QYWX_AM" != "" ];then
            python py/notify_dayepao.py "Github Keepalive" "${MESSAGE_CONTENT}"
          fi
