name: keepalive

on:
  workflow_dispatch:
  schedule:
    - cron: 0 13 1,15 * *

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Set time zone
        run: |
          sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Update keepalive
        run: |
          repos="personal_actions backup" #仓库名称
          message_content="$(date)\n\n"
          for repo in $repos
          do
          git clone https://github.com/${{ github.actor }}/${repo}
          cd ${repo}
          echo "$(date)" > keepalive
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add keepalive
          git commit -m "Update keepalive" -a
          git push "https://${{ github.actor }}:${{ secrets.GH_PAT }}@github.com/${{ github.actor }}/${repo}.git"
          message_content="${message_content}${repo}保活成功\n\n"
          cd ..
          done
          echo "MESSAGE_CONTENT=${message_content}" >> $GITHUB_ENV
      - name: Push message
        env:
          QYWX_AM: ${{ secrets.QYWX_AM }}
        run: |
          if [ "QYWX_AM" != "" ];then
            python notify_dayepao.py "keepalive" "${PUSHDATA}"
          fi
